name: venv
channels:
  - defaults
  - conda-forge
dependencies:
  - jupyterlab=4.0.2
  - keras=2.13.1
  - plotly=5.15.0
  - seaborn=0.12.2
  - tensorflow=2.13.0
  - python-pptx=0.6.21
  - moviepy=1.0.3
  - pandas=2.0.2
  - pip
  - pip:
    - ffmpeg-python==0.2.0
    - gTTS==2.3.2
    - pdf2image==1.16.3
    - tqdm==4.64.1
