name: Continuous Integration

on:
  push:
    paths:
      - 'Dockerfile'
    branches: [dev, main]
  pull_request:
    paths:
      - 'Dockerfile'
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  packages: write
  pull-requests: read

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout dev branch
      uses: actions/checkout@v3.5.3
      with:
        ref: dev
        fetch-depth: '0'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Login to GitHub Packages
      uses: docker/login-action@v2.2.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ghcr.io/${{ github.repository }}/build:${{ github.sha }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache

  build:
    needs: docker
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}/build:${{ github.sha }}
    steps:
      - name: Check out dev branch
        uses: actions/checkout@v3.5.3
        with:
          ref: dev

      - name: Set up Python
        uses: actions/setup-python@v4.6.1
        with:
          python-version: "3.11.3"

      - name: Generate Project Report PDF
        run: |
          pdflatex Final-Project-Report-Team-2.tex
          pdflatex Project-Proposal-Team-2.tex

      - name: Upload Project Report PDFs
        uses: actions/upload-artifact@v2
        with:
          name: documents
          path: |
            Final-Project-Report-Team-2.pdf
            Project-Proposal-Team-2.pdf

  release:
    needs: build
    if: github.event.pull_request.merged == true && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:

      - name: Checkout main branch
        uses: actions/checkout@v3.5.3
        with:
          ref: main
          fetch-depth: '0'

      - name: Download artifacts
        uses: actions/download-artifact@v2.1.1
        with:
          name: documents

      - name: Get Version
        run: echo "version=$(cat release.txt)" >> $GITHUB_ENV

      - name: Print Version
        run: echo "Version is ${{ env.version }}"

      - name: Release
        uses: softprops/action-gh-release@v0.1.15
        with:
          tag_name: ${{ env.version }}
          files: |
            Project-Proposal-Team-2.pdf
            Final-Project-Report-Team-2.pdf
            Final-Project-Team-2.mp4
          body: |
            DELIVERABLES:
              - [Project-Proposal-Team-2.pdf](https://github.com/team2-su23-aai501/project/releases/download/${{ env.version }}/Project-Proposal-Team-2.pdf)
              - [Final-Project-Report-Team-2.pdf](https://github.com/team2-su23-aai501/project/releases/download/${{ env.version }}/Final-Project-Report-Team-2.pdf)
              - [Final-Project-Report-Team-2.mp4](https://github.com/team2-su23-aai501/project/releases/download/${{ env.version }}/Final-Project-Team-2.mp4)
          draft: false
          prerelease: true
