name: Delete Artifacts

on:
  workflow_dispatch:

jobs:
  delete_artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Delete All Artifacts
        uses: jimschubert/delete-artifacts-action@v1
        with:
          log_level: 'error'
          min_bytes: '0'
