name: Pull Request

on:
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  packages: write
  pull-requests: read

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout dev branch
      uses: actions/checkout@v3.5.3
      with:
        ref: dev
        fetch-depth: '0'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.0

    - name: Generate Dockerfile hash
      id: dockerfile
      run: echo "::set-output name=hash::$(sha256sum Dockerfile | cut -d ' ' -f1)"

    - name: Cache Docker layers
      uses: actions/cache@v1.2.1
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ steps.dockerfile.outputs.hash }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Login to GitHub Packages
      uses: docker/login-action@v2.2.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4.1.1
      with:
        context: .
        push: true
        tags: |
          ghcr.io/${{ github.repository }}/build:${{ github.sha }}
          ${{ github.event_name == 'pull_request' && github.event.action == 'closed' && 'ghcr.io/${{ github.repository }}/build:latest' }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache,mode=max

    - name: Save Docker layers
      uses: actions/cache@v1.2.1
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ steps.dockerfile.outputs.hash }}
        restore-keys: |
          ${{ runner.os }}-buildx-
      if: always()

  build:
    needs: docker
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}/build:${{ github.sha }}
    steps:
      - name: Check out dev branch
        uses: actions/checkout@v3.5.3
        with:
          ref: dev
          fetch-depth: '0'

      - name: Set up Python
        uses: actions/setup-python@v4.6.1
        with:
          python-version: "3.11.3"

      - name: Generate Project Report PDF
        run: |
          pdflatex Final-Project-Report-Team-2.tex
          pdflatex Project-Proposal-Team-2.tex

      - name: Upload Project Report PDFs
        uses: actions/upload-artifact@v3.1.2
        with:
          name: documents
          path: |
            Final-Project-Report-Team-2.pdf
            Project-Proposal-Team-2.pdf
