name: Pull Request

on:
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  packages: read

jobs:
  build:
    container:
      image: ghcr.io/team2-su23-aai501/build-project:latest
    runs-on: ubuntu-latest
    steps:
      - name: Check out dev branch
        uses: actions/checkout@v3.5.3
        with:
          ref: dev
          fetch-depth: '0'

      - name: Print out pip list
        run: |
          pip list

      - name: Generate PDFs
        run: |
          # must generate twice
          pdflatex Final-Project-Report-Team-2.tex
          pdflatex Final-Project-Report-Team-2.tex
          pdflatex Project-Proposal-Team-2.tex
          pdflatex Project-Proposal-Team-2.tex

      - name: Generate Video
        run: |
          python3 pptx2video.py Final-Project-Team-2.pptx
          ls -l Final-Project-Team-2.mp4
