name: Release

on:
  pull_request:
    types: [closed]
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Check out main branch
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: '0'

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.11.3"

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Cache APT Packages
        uses: actions/cache@v3
        with:
          path: |
            /var/cache/apt/archives/**.deb
            !/var/cache/apt/archives/partial
            !/var/cache/apt/archives/lock
          key: ${{ runner.os }}-apt-${{ hashFiles('apt.txt') }}
          restore-keys: ${{ runner.os }}-apt-

      - name: Generate project report PDF
        run: |
          # INSTALL PYTHON DEPENDENCIES
          python3 -m pip install --upgrade pip
          pip install nbconvert ipykernel
          python3 -m ipykernel install --user

          # INSTALL APT DEPENDENCIES
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-xetex
          pip install nbconvert jupyterlab

          # CONVERT NOTEBOOK TO PDF
          jupyter nbconvert --to pdf --execute project.ipynb --output Final-Project-Report-Team-2.pdf

      - name: Get short SHA
        run: echo "SHORT_SHA=$(echo ${GITHUB_SHA::7})" >> $GITHUB_ENV

      - name: Bump version and push tag
        id: tag_version
        uses: anothrNick/github-tag-action@1.34.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          PRERELEASE: true
          DEFAULT_BUMP: patch

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: Release ${{ steps.tag_version.outputs.new_tag }}
          files: |
            Final-Project-Team-2.mp4
            Final-Project-Report-Team-2.pdf
          body: |
            DELIVERABLES:
            - [Final-Project-Report-Team-2.pdf](https://github.com/team2-su23-aai501/project/releases/download/${{ steps.tag_version.outputs.new_tag }}/Final-Project-Report-Team-2.pdf)
            - [Final-Project-Report-Team-2.pdf](https://github.com/team2-su23-aai501/project/releases/download/${{ steps.tag_version.outputs.new_tag }}/Final-Project-Team-2.mp4)
          draft: false
          prerelease: true
