name: Release

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out main branch
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: '0'

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.11.3"

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Cache APT Packages
        uses: actions/cache@v3
        with:
          path: |
            /var/cache/apt/archives/**.deb
            !/var/cache/apt/archives/partial
            !/var/cache/apt/archives/lock
          key: ${{ runner.os }}-apt-${{ hashFiles('apt.txt') }}
          restore-keys: ${{ runner.os }}-apt-

      - name: Test - Generate Project Report PDF
        run: |
          # INSTALL PYTHON DEPENDENCIES
          python3 -m pip install --upgrade pip
          pip install nbconvert ipykernel
          python3 -m pip install ipykernel nbconvert jupyterlab --user

          # INSTALL APT DEPENDENCIES
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-xetex

          # CONVERT NOTEBOOK TO PDF
          jupyter nbconvert --to pdf --execute project.ipynb --output Final-Project-Report-Team-2-NO-COVER.pdf

      - name: Add cover to the report
        run: |
          # INSTALL APT DEPENDENCIES
          sudo apt-get update
          sudo apt-get install -y pdftk

          # ADD COVER
          pdftk cover.pdf Final-Project-Report-Team-2-NO-COVER.pdf cat output Final-Project-Report-Team-2.pdf

      - name: Get Version
        id: get_version
        run: echo "version=$(cat release.txt)" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v0.1.15
        with:
          tag_name: ${{ env.version }}
          files: |
            Final-Project-Team-2.mp4
            Final-Project-Report-Team-2.pdf
          body: |
            DELIVERABLES:
            - [Final-Project-Report-Team-2.mp4](https://github.com/team2-su23-aai501/project/releases/download/${{ env.version }}/Final-Project-Team-2.mp4)
            - [Final-Project-Report-Team-2.pdf](https://github.com/team2-su23-aai501/project/releases/download/${{ env.version }}/Final-Project-Report-Team-2.pdf)
          draft: false
          prerelease: true
