name: Release

on:
  pull_request:
    branches: [main]
    types: [closed]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  packages: write
  pull-requests: read

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}/build:latest
    steps:
      - name: Check out dev branch
        uses: actions/checkout@v3.5.3
        with:
          ref: dev
          fetch-depth: '0'

      - name: Set up Python
        uses: actions/setup-python@v4.6.1
        with:
          python-version: "3.11.3"

      - name: Generate Project Report PDF
        run: |
          rm Final-Project-Report-Team-2.pdf
          pdflatex Final-Project-Report-Team-2.tex

          rm Project-Proposal-Team-2.pdf
          pdflatex Project-Proposal-Team-2.tex

      - name: Upload Project Report PDFs
        uses: actions/upload-artifact@v3.1.2
        with:
          name: documents
          path: |
            Final-Project-Report-Team-2.pdf
            Project-Proposal-Team-2.pdf
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3.5.3
        with:
          ref: main
          fetch-depth: '0'

      - name: Download artifacts
        uses: actions/download-artifact@v2.1.1
        with:
          name: documents

      - name: Get Version
        run: echo "version=$(cat release.txt)" >> $GITHUB_ENV

      - name: Print Version
        run: echo "Version is ${{ env.version }}"

      - name: Release
        uses: softprops/action-gh-release@v0.1.15
        with:
          tag_name: ${{ env.version }}
          files: |
            Project-Proposal-Team-2.pdf
            Final-Project-Report-Team-2.pdf
            Final-Project-Team-2.mp4
          body: |
            DELIVERABLES:
              - [Project-Proposal-Team-2.pdf](https://github.com/team2-su23-aai501/project/releases/download/${{ env.version }}/Project-Proposal-Team-2.pdf)
              - [Final-Project-Report-Team-2.pdf](https://github.com/team2-su23-aai501/project/releases/download/${{ env.version }}/Final-Project-Report-Team-2.pdf)
              - [Final-Project-Report-Team-2.mp4](https://github.com/team2-su23-aai501/project/releases/download/${{ env.version }}/Final-Project-Team-2.mp4)
          draft: false
          prerelease: true
