name: Release

on:
  pull_request:
    branches: [main]
    types: [closed]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  packages: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out dev branch
        uses: actions/checkout@v3.5.3
        with:
          ref: dev
          fetch-depth: '0'

      - name: Run container
        run: |
          docker run -d --name build-container -v $PWD:/workspace ghcr.io/team2-su23-aai501/build-project:latest

      - name: Generate Project Deliverables
        run: |
          docker exec build-container bash -c "pdflatex /workspace/Final-Project-Report-Team-2.tex"
          docker exec build-container bash -c "pdflatex /workspace/Final-Project-Report-Team-2.tex"
          docker exec build-container bash -c "pdflatex /workspace/Project-Proposal-Team-2.tex"
          docker exec build-container bash -c "pdflatex /workspace/Project-Proposal-Team-2.tex"
          docker exec build-container bash -c "python3 /workspace/pptx2video.py /workspace/Final-Project-Team-2.pptx"

          # check if files exist
          docker exec build-container bash -c "ls -l /workspace/Final-Project-Report-Team-2.pdf"
          docker exec build-container bash -c "ls -l /workspace/Project-Proposal-Team-2.pdf"
          docker exec build-container bash -c "ls -l /workspace/Final-Project-Team-2.mp4"

      - name: Get Version
        run: |
          echo "version=$(cat release.txt)" >> $GITHUB_ENV
          echo "Release Version: ${{ env.version }}"

      - name: Release
        uses: softprops/action-gh-release@v0.1.15
        with:
          tag_name: ${{ env.version }}
          files: |
            Project-Proposal-Team-2.pdf
            Final-Project-Report-Team-2.pdf
            Final-Project-Team-2.mp4
          body: |
            DELIVERABLES:
              - [Project-Proposal-Team-2.pdf](https://github.com/team2-su23-aai501/project/releases/download/${{ env.version }}/Project-Proposal-Team-2.pdf)
              - [Final-Project-Report-Team-2.pdf](https://github.com/team2-su23-aai501/project/releases/download/${{ env.version }}/Final-Project-Report-Team-2.pdf)
              - [Final-Project-Team-2.mp4](https://github.com/team2-su23-aai501/project/releases/download/${{ env.version }}/Final-Project-Team-2.mp4)
          draft: false
          prerelease: true
