name: Test

on:
  push:
    branches: [dev]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  packages: read

jobs:
  build-pdfs:
    runs-on: ubuntu-latest
    container:
      image: texlive/texlive:latest
    steps:
      - name: Check out dev branch
        uses: actions/checkout@v3.5.3
        with:
          ref: dev
          fetch-depth: '0'

      - name: Generate PDFs
        run: |
          # must generate twice
          pdflatex Final-Project-Report-Team-2.tex
          pdflatex Final-Project-Report-Team-2.tex
          pdflatex Project-Proposal-Team-2.tex
          pdflatex Project-Proposal-Team-2.tex

  build-video:
    runs-on: ubuntu-latest
    steps:
      - name: Check out dev branch
        uses: actions/checkout@v3.5.3
        with:
          ref: dev
          fetch-depth: '0'

      - name: Install Dependencies
        run: |
          sudo apt-get update

          sudo apt-get -y install \
            ffmpeg \
            libreoffice \
            poppler-utils

          pip install \
            ffmpeg_python \
            gTTS  \
            moviepy \
            pdf2image  \
            python-pptx

      - name: Generate Video
        run: |
          python3 pptx2video.py Final-Project-Team-2.pptx
          ls -al
