name: Test

on:
  push:
    branches: [dev]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  packages: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out dev branch
        uses: actions/checkout@v3.5.3
        with:
          ref: dev
          fetch-depth: '0'

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Run container
        run: |
          docker run -d --name build-container -v $PWD:/workspace ghcr.io/team2-su23-aai501/build-project:latest tail -f /dev/null

      - name: Generate Project Deliverables
        run: |
          docker exec build-container bash -c "pdflatex /workspace/Final-Project-Report-Team-2.tex"
          docker exec build-container bash -c "pdflatex /workspace/Final-Project-Report-Team-2.tex"
          docker exec build-container bash -c "pdflatex /workspace/Project-Proposal-Team-2.tex"
          docker exec build-container bash -c "pdflatex /workspace/Project-Proposal-Team-2.tex"
          docker exec build-container bash -c "python3 /workspace/pptx2video.py /workspace/Final-Project-Team-2.pptx"

          # check if files exist
          docker exec build-container bash -c "ls -l /workspace/Final-Project-Report-Team-2.pdf"
          docker exec build-container bash -c "ls -l /workspace/Project-Proposal-Team-2.pdf"
          docker exec build-container bash -c "ls -l /workspace/Final-Project-Team-2.mp4"

      - name: Logout of GitHub Container Registry
        run: docker logout ghcr.io
        if: always()
